openapi: 3.0.3
info:
  title: Todo Backend API - Task Management
  description: |
    RESTful API for managing todo tasks with strict per-user data isolation.
    All endpoints require JWT authentication via Bearer token.

    **Security**: User identity is extracted from JWT token, not from client input.
    All operations are automatically scoped to the authenticated user.
  version: 1.0.0
  contact:
    name: Todo Backend API
    url: https://github.com/your-repo/todo-backend-api

servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.yourdomain.com
    description: Production server

security:
  - BearerAuth: []

tags:
  - name: Tasks
    description: Task management operations (CRUD + completion toggle)

paths:
  /api/tasks:
    get:
      tags:
        - Tasks
      summary: List all tasks for authenticated user
      description: |
        Retrieves all tasks owned by the authenticated user.
        Tasks are automatically filtered by user_id from JWT token.
        Returns tasks sorted by creation date (newest first).
      operationId: listTasks
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully retrieved task list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'
              examples:
                emptyList:
                  summary: No tasks
                  value: []
                withTasks:
                  summary: User with tasks
                  value:
                    - id: "550e8400-e29b-41d4-a716-446655440000"
                      title: "Buy groceries"
                      description: "Milk, eggs, bread"
                      completed: false
                      user_id: "123e4567-e89b-12d3-a456-426614174000"
                      created_at: "2026-02-06T10:30:00Z"
                      updated_at: "2026-02-06T10:30:00Z"
                    - id: "660e8400-e29b-41d4-a716-446655440001"
                      title: "Finish project report"
                      description: null
                      completed: true
                      user_id: "123e4567-e89b-12d3-a456-426614174000"
                      created_at: "2026-02-05T14:20:00Z"
                      updated_at: "2026-02-06T09:15:00Z"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      tags:
        - Tasks
      summary: Create a new task
      description: |
        Creates a new task for the authenticated user.
        User ID is automatically extracted from JWT token.
        Task starts with completed=false.
      operationId: createTask
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
            examples:
              withDescription:
                summary: Task with description
                value:
                  title: "Buy groceries"
                  description: "Milk, eggs, bread"
              withoutDescription:
                summary: Task without description
                value:
                  title: "Call dentist"
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                title: "Buy groceries"
                description: "Milk, eggs, bread"
                completed: false
                user_id: "123e4567-e89b-12d3-a456-426614174000"
                created_at: "2026-02-06T10:30:00Z"
                updated_at: "2026-02-06T10:30:00Z"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/tasks/{task_id}:
    get:
      tags:
        - Tasks
      summary: Get a specific task by ID
      description: |
        Retrieves a single task by ID.
        Returns 404 if task doesn't exist or user doesn't own it (prevents enumeration).
      operationId: getTask
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          description: Task retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                title: "Buy groceries"
                description: "Milk, eggs, bread"
                completed: false
                user_id: "123e4567-e89b-12d3-a456-426614174000"
                created_at: "2026-02-06T10:30:00Z"
                updated_at: "2026-02-06T10:30:00Z"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      tags:
        - Tasks
      summary: Update a task
      description: |
        Updates title and description of an existing task.
        User must own the task (ownership verified).
        Completion status is updated via separate PATCH endpoint.
      operationId: updateTask
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
            example:
              title: "Buy organic groceries"
              description: "Almond milk, free-range eggs, whole wheat bread"
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                title: "Buy organic groceries"
                description: "Almond milk, free-range eggs, whole wheat bread"
                completed: false
                user_id: "123e4567-e89b-12d3-a456-426614174000"
                created_at: "2026-02-06T10:30:00Z"
                updated_at: "2026-02-06T11:45:00Z"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags:
        - Tasks
      summary: Delete a task
      description: |
        Permanently deletes a task.
        User must own the task (ownership verified).
        Deletion is permanent (no soft delete).
      operationId: deleteTask
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '204':
          description: Task deleted successfully (no content)
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/tasks/{task_id}/complete:
    patch:
      tags:
        - Tasks
      summary: Toggle task completion status
      description: |
        Toggles the completion status of a task.
        If completed=false, sets to true. If completed=true, sets to false.
        User must own the task (ownership verified).
      operationId: toggleTaskCompletion
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          description: Task completion status toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                title: "Buy groceries"
                description: "Milk, eggs, bread"
                completed: true
                user_id: "123e4567-e89b-12d3-a456-426614174000"
                created_at: "2026-02-06T10:30:00Z"
                updated_at: "2026-02-06T12:00:00Z"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token obtained from authentication endpoints.
        Format: Authorization: Bearer <token>

  parameters:
    TaskId:
      name: task_id
      in: path
      required: true
      description: UUID of the task
      schema:
        type: string
        format: uuid
      example: "550e8400-e29b-41d4-a716-446655440000"

  schemas:
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 500
          description: Task title (required, 1-500 characters)
          example: "Buy groceries"
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Optional task description (0-2000 characters)
          example: "Milk, eggs, bread"

    TaskUpdate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 500
          description: New task title (required, 1-500 characters)
          example: "Buy organic groceries"
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: New task description (optional, 0-2000 characters)
          example: "Almond milk, free-range eggs, whole wheat bread"

    TaskResponse:
      type: object
      required:
        - id
        - title
        - completed
        - user_id
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique task identifier
          example: "550e8400-e29b-41d4-a716-446655440000"
        title:
          type: string
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          description: Task description (null if not provided)
          example: "Milk, eggs, bread"
        completed:
          type: boolean
          description: Task completion status
          example: false
        user_id:
          type: string
          format: uuid
          description: Owner user ID (from JWT token)
          example: "123e4567-e89b-12d3-a456-426614174000"
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp (UTC)
          example: "2026-02-06T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp (UTC)
          example: "2026-02-06T10:30:00Z"

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Task not found"

    ValidationErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
                description: Location of the error (field path)
                example: ["body", "title"]
              msg:
                type: string
                description: Error message
                example: "field required"
              type:
                type: string
                description: Error type
                example: "value_error.missing"

  responses:
    BadRequest:
      description: Bad request - invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            emptyTitle:
              summary: Empty title
              value:
                detail: "Title cannot be empty"
            titleTooLong:
              summary: Title too long
              value:
                detail: "Title cannot exceed 500 characters"

    Unauthorized:
      description: Unauthorized - missing or invalid JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            missingToken:
              summary: Missing token
              value:
                detail: "Not authenticated"
            invalidToken:
              summary: Invalid token
              value:
                detail: "Invalid authentication credentials"
            expiredToken:
              summary: Expired token
              value:
                detail: "Token has expired"

    NotFound:
      description: Not found - task doesn't exist or user doesn't own it
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Task not found"

    ValidationError:
      description: Validation error - request body doesn't match schema
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationErrorResponse'
          example:
            detail:
              - loc: ["body", "title"]
                msg: "field required"
                type: "value_error.missing"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Internal server error"
